In [0]:
df = pd.read_csv('epolis.csv',encoding='utf-8')

In [0]:
df.shape

(3888, 57)

In [0]:
df.head()

   Unnamed: 0     address.coordinates.coordinates  ...         lat       long
0           0  [100.57029591131, 13.731550581483]  ...  100.570296  13.731551
1           1  [100.55620782546, 13.806206734004]  ...  100.556208  13.806207
2           2             [100.566444, 13.743262]  ...  100.566444  13.743262
3           3   [100.58022754954, 13.72258985005]  ...  100.580228  13.722590
4           4   [100.51066044233, 13.72752828353]  ...  100.510660  13.727528

[5 rows x 57 columns]

In [0]:
df.columns

Index(['Unnamed: 0', 'address.coordinates.coordinates',
       'address.coordinates.type', 'address.id', 'address.origin_id',
       'address.translate', 'address_id', 'agency_reference', 'conditions',
       'condo.common_fee', 'condo.created_at', 'condo.deleted_at',
       'condo.finish_construction_date', 'condo.id', 'condo.name',
       'condo.old_id', 'condo.parking_slot_amount',
       'condo.parking_slot_percentage', 'condo.presale_date',
       'condo.published_at', 'condo.start_construction_date',
       'condo.thumbnail_url', 'condo.unit_amount', 'condo.updated_at',
       'condo.website', 'condo_id', 'condo_name', 'contract_advance',
       'contract_deposit', 'contract_length', 'created_at', 'deleted_at',
       'detail.balcony_direction', 'detail.bathroom_amount',
       'detail.bedroom_amount', 'detail.building', 'detail.floor',
       'detail.otherroom_amount', 'detail.parking_slot',
       'detail.plan_picture_url', 'detail.property_broker',
       'detail.thumbnail_url', 'full_address', 'highlights', 'id',
       'new_condo_id', 'post_description', 'post_title', 'price_balance',
       'price_down', 'price_per_sqm', 'price_rent', 'price_sell', 'room_size',
       'updated_at', 'lat', 'long'],
      dtype='object')

### Remove the columns that contains no data

In [0]:
df.isnull().sum(axis=0)

Unnamed: 0                            0
address.coordinates.coordinates       0
address.coordinates.type              0
address.id                            0
address.origin_id                     0
address.translate                     0
address_id                            0
agency_reference                   1963
conditions                            0
condo.common_fee                      0
condo.created_at                      0
condo.deleted_at                   3888
condo.finish_construction_date     3888
condo.id                              0
condo.name                            0
condo.old_id                          0
condo.parking_slot_amount             0
condo.parking_slot_percentage         0
condo.presale_date                 3888
condo.published_at                    4
condo.start_construction_date      3888
condo.thumbnail_url                1437
condo.unit_amount                     0
condo.updated_at                      0
condo.website                      3816
condo_id                              0
condo_name                            0
contract_advance                   3237
contract_deposit                   3237
contract_length                    3237
created_at                            0
deleted_at                         3888
detail.balcony_direction           2972
detail.bathroom_amount                0
detail.bedroom_amount                 0
detail.building                    2466
detail.floor                        972
detail.otherroom_amount               0
detail.parking_slot                   0
detail.plan_picture_url               0
detail.property_broker                2
detail.thumbnail_url                  0
full_address                          0
highlights                            0
id                                    0
new_condo_id                          0
post_description                      0
post_title                            0
price_balance                      3888
price_down                         3888
price_per_sqm                         0
price_rent                         3237
price_sell                            0
room_size                             0
updated_at                            0
lat                                   0
long                                  0
dtype: int64

In [0]:
nrow=df.shape[0]
NAcols = df.isnull().sum(axis=0).tolist() == np.repeat(nrow,df.shape[1])
print(df.columns[~NAcols])
df = df[df.columns[~NAcols]]

Index(['Unnamed: 0', 'address.coordinates.coordinates',
       'address.coordinates.type', 'address.id', 'address.origin_id',
       'address.translate', 'address_id', 'agency_reference', 'conditions',
       'condo.common_fee', 'condo.created_at', 'condo.id', 'condo.name',
       'condo.old_id', 'condo.parking_slot_amount',
       'condo.parking_slot_percentage', 'condo.published_at',
       'condo.thumbnail_url', 'condo.unit_amount', 'condo.updated_at',
       'condo.website', 'condo_id', 'condo_name', 'contract_advance',
       'contract_deposit', 'contract_length', 'created_at',
       'detail.balcony_direction', 'detail.bathroom_amount',
       'detail.bedroom_amount', 'detail.building', 'detail.floor',
       'detail.otherroom_amount', 'detail.parking_slot',
       'detail.plan_picture_url', 'detail.property_broker',
       'detail.thumbnail_url', 'full_address', 'highlights', 'id',
       'new_condo_id', 'post_description', 'post_title', 'price_per_sqm',
       'price_rent', 'price_sell', 'room_size', 'updated_at', 'lat', 'long'],
      dtype='object')

### By looking at the data drop other columns

In [0]:
print(df['condo.created_at'].isna().sum())
print(df['condo.created_at'].max())
print(df['condo.created_at'].min())

0
2019-05-02 15:04:17
2018-11-07 17:16:17

Since the range is only one year, this column is not very useful

In [0]:
unwantedCols = ['address.id', 'address.origin_id',
       'address.translate', 'address_id', 'agency_reference', 'conditions',
       'condo.created_at', 'condo.name',
       'condo.old_id',
       'condo.published_at',
       'condo.thumbnail_url', 'condo.updated_at',
       'condo.website', 'condo_id',
       'contract_advance', 'contract_deposit', 'contract_length', #most are NA
       'created_at',
       'detail.balcony_direction', #most are NA
       'detail.building',
       'detail.plan_picture_url', 'detail.property_broker',
       'detail.thumbnail_url', 'highlights','id',
       'post_description', 'post_title',
       'updated_at']
df = df[[c for c in df.columns if c not in unwantedCols]]
df.columns

Index(['Unnamed: 0', 'address.coordinates.coordinates',
       'address.coordinates.type', 'condo.common_fee', 'condo.id',
       'condo.parking_slot_amount', 'condo.parking_slot_percentage',
       'condo.unit_amount', 'condo_name', 'detail.bathroom_amount',
       'detail.bedroom_amount', 'detail.floor', 'detail.otherroom_amount',
       'detail.parking_slot', 'full_address', 'new_condo_id', 'price_per_sqm',
       'price_rent', 'price_sell', 'room_size', 'lat', 'long'],
      dtype='object')

Dropping text columns, less populated columns, dates that are web metadata, URL.

In [0]:
df.head()

   Unnamed: 0     address.coordinates.coordinates  ...         lat       long
0           0  [100.57029591131, 13.731550581483]  ...  100.570296  13.731551
1           1  [100.55620782546, 13.806206734004]  ...  100.556208  13.806207
2           2             [100.566444, 13.743262]  ...  100.566444  13.743262
3           3   [100.58022754954, 13.72258985005]  ...  100.580228  13.722590
4           4   [100.51066044233, 13.72752828353]  ...  100.510660  13.727528

[5 rows x 22 columns]

In [0]:
df.to_csv("clean_data.csv")